import type { NextPage } from "next";
import Head from "next/head";
import { BackButton } from "../components";
import Heading from "../components/Heading";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bootcamp Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid place-items-center gap-5 w-full min-h-screen bg-slate-300 grid-cols-1">
        <div className="grid place-items-center gap-5 w-1/3">
          <BackButton />
          <Heading text="About Bootcamp Buddy" />
          <p className="my-4">
            A site to aid the creation of bootcamp workouts. Made using NextJS.
          </p>
        </div>
      </main>
    </div>
  );
};

export default About;
