import type { NextPage } from "next";
import Head from "next/head";
import { BackButton } from "../components";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bootcamp Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-items-center justify-evenly	 h-screen ">
        <BackButton />
        <h1 className="text-3xl bold">About Bootcamp Buddy</h1>

        <p>
          A site to aid the creation of bootcamp workouts. Made using NextJS.
        </p>
      </main>
    </div>
  );
};

export default About;
