import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HomeLink } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bootcamp Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-items-center justify-evenly	 h-screen ">
        <h1 className="text-3xl bold">🏋️ Bootcamp Buddy! 🏋️</h1>

        <HomeLink
          title="Create"
          linkText="Create your bootcamp workout!"
          link="/workout/create"
        />

        <HomeLink
          title="View"
          linkText="View your workouts!"
          link="/workout/view"
        />
      </main>
    </div>
  );
};

export default Home;
