import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bootcamp Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bootcamp Buddy!</h1>

        <p className={styles.description}>Let&apos;s get started!</p>

        <Link href="/workout/create">
          <a className={styles.card}>
            <h2>Create &rarr;</h2>
            <p>Create your bootcamp workout!</p>
          </a>
        </Link>
        <Link href="/workout/view">
          <a className={styles.card}>
            <h2>View &rarr;</h2>
            <p>View your workouts!</p>
          </a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
