import type { NextPage } from "next";
import Head from "next/head";
import { HomeLink } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bootcamp Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid place-items-center gap-5 m-5 w-full">
        <h1 className="text-3xl bold">🏋️ Bootcamp Buddy! 🏋️</h1>
        <div className="grid md:grid-cols-3 gap-1 w-2/3 my-10">
          <HomeLink title="Create workout" link="/workout/create" />
          <HomeLink title="View workout" link="/workout/view" />
          <HomeLink title="About" link="/about" />
        </div>
      </main>
    </div>
  );
};

export default Home;
