import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const View: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Your workouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <a>
          <h2>Go Back</h2>
        </a>
      </Link>
      <h1>View workouts</h1>
    </div>
  );
};

export default View;
