import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const View: NextPage = () => {
  return (
    <div className="grid place-items-center h-screen ">
      <Head>
        <title>Your workouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <a>
          <h2>Go Back</h2>
        </a>
      </Link>
      <h1 className="text-3xl">View workouts</h1>
    </div>
  );
};

export default View;
